spring.application.name=backend

server.port = 8000

spring.datasource.url = jdbc:postgresql://localhost:5432/Uptime-Maintenance-log-reporting-app
spring.datasource.username = postgres
spring.datasource.password = mangal@123

spring.jpa.hibernate.ddl-auto = update
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.security.employee.name = mangal
spring.security.employee.password = mangal@123
jwt.secret=VGhpc0lzQVN1cGVyU2VjcmV0S2V5Rm9ySldUU3ByaW5nQm9vdA==
jwt.expiration_time=1800000