spring.config.import=optional:file:.env[.properties]

spring.application.name=backend

server.port = 8000

#spring.datasource.url = jdbc:postgresql://aws-1-ap-southeast-2.pooler.supabase.com:5432/postgres?user=${SUPABASE_USER}&password=${SUPABASE_PWD}
spring.datasource.url = jdbc:postgresql://localhost:5432/${DB_NAME}
spring.datasource.username = ${DB_USER}
spring.datasource.password = ${DB_PASSWORD}
#jdbc:postgresql://db.rmuephjmuiamkclawgje.supabase.co:5432/postgres?user=postgres&password=Mangal_dev%402026

spring.jpa.hibernate.ddl-auto = update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true

spring.security.employee.name = mangal
spring.security.employee.password = mangal@123
jwt.secret = ${JWT_SECRET}
jwt.expiration_time = ${JWT_EXPIRATION}
